runtime: nodejs22

handlers:
  - url: /static
    static_dir: build/static
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"

